pub(crate) const SKILL_NAMES: [&str; 134] = [
    "",
    "Attack Boost",
    "Agitator",
    "Peak Performance",
    "Resentment",
    "Resuscitate",
    "Critical Eye",
    "Critical Boost",
    "Weakness Exploit",
    "Latent Power",
    "Maximum Might",
    "Critical Element",
    "Master's Touch",
    "Fire Attack",
    "Water Attack",
    "Ice Attack",
    "Thunder Attack",
    "Dragon Attack",
    "Poison Attack",
    "Paralysis Attack",
    "Sleep Attack",
    "Blast Attack",
    "Handicraft",
    "Razor Sharp",
    "Spare Shot",
    "Protective Polish",
    "Mind's Eye",
    "Aim Booster",
    "Bludgeoner",
    "Bow Charge Plus",
    "Focus",
    "Power Prolonger",
    "Marathon Runner",
    "Constitution",
    "Stamina Surge",
    "Guard",
    "Guard Up",
    "Offensive Guard",
    "Critical Draw",
    "Punishing Draw",
    "Quick Sheathe",
    "Slugger",
    "Stamina Thief",
    "Affinity Sliding",
    "Horn Maestro",
    "Artillery",
    "Load Shells",
    "Special Ammo Boost",
    "Normal/Rapid Up",
    "Pierce Up",
    "Spread Up",
    "Ammo Up",
    "Reload Speed",
    "Recoil Down",
    "Steadiness",
    "Rapid Fire Up",
    "Defense Boost",
    "Divine Blessing",
    "Recovery Up",
    "Recovery Speed",
    "Speed Eating",
    "Earplugs",
    "Windproof",
    "Tremor Resitance",
    "Bubbly Dance",
    "Evade Window",
    "Evade Extender",
    "Fire Resistance",
    "Water Resistance",
    "Ice Resistance",
    "Thunder Resistance",
    "Dragon Resistance",
    "Blight Resistance",
    "Poison Resistance",
    "Paralysis Resistance",
    "Sleep Resistance",
    "Stun Resistance",
    "Muck Resistance",
    "Blast Resistance",
    "Botanist",
    "Geologist",
    "Partbreaker",
    "Capture Master",
    "Carving Master",
    "Good Luck",
    "Speed Sharpening",
    "Bombardier",
    "Mushroomancer",
    "Item Prolonger",
    "Wide-Range",
    "Free Meal",
    "Heroics",
    "Fortify",
    "Flinch Free",
    "Jump Master",
    "Carving Pro",
    "Hunger Resistance",
    "Leap of Faith",
    "Diversion",
    "Master Mounter",
    "Chameleos Blessing",
    "Kushala Blessing",
    "Teostra Blessing",
    "Dragonheart",
    "Wirebug Whisperer",
    "Wall Runner",
    "Counterstrike",
    "Rapid Morph",
    "Hellfire Cloak",
    "Wind Alignment",
    "Thunder Alignment",
    "Stormsoul",
    "Blood Rite",
    "Dereliction",
    "Furious",
    "Mail of Hellfire",
    "Coalescence",
    "Bloodlust",
    "",
    "",
    "",
    "",
    "Redirection",
    "Spiribird's Call",
    "Charge Master",
    "Foray",
    "Tune-Up",
    "Grinder (S)",
    "Bladescale Hone",
    "Wall Runner (Boost)",
    "",
    "Chain Crit",
    "",
    "Quick Breath",
];

pub(crate) const CHARM_EQUIPMENT_TYPE: u32 = 3;

pub(crate) mod offsets {
    pub const STORAGE_BASE: usize = 0x14E96B280;
    // equipment box = [[[STORAGE_BASE+0x88]+0x98]+0x10]
    pub const EQUIPMENT_LIST: usize = 0x20;
    pub const EQUIPMENT_SIZE: usize = 0x1C;

    pub const EQUIPMENT_TYPE: usize = 0x2C;

    pub const SLOT_POINTER: usize = 0x70;
    pub const SLOT_VALUES: usize = 0x24;

    pub const SKILL_ID_POINTER: usize = 0x78;
    pub const SKILL_ID_VALUES: usize = 0x20;

    pub const SKILL_LVL_POINTER: usize = 0x80;
    pub const SKILL_LVL_VALUES: usize = 0x20;
}
